language: python
python:
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
before_install:
  - export TZ=Asia/Jerusalem
install:
  - pip install -r requirements.txt
  - pip install codecov
# command to run tests
script:
  - pytest -v --cov=./
  - codecov
