language: python
python:
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
# command to install dependencies
services:
  - docker
before_install:
  - export TZ=Asia/Jerusalem
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install flake8
  - docker run -d --name rabbit -p 5672:5672 rabbitmq
  - docker run -d --name mongo -p 27017:27017 mongo
# command to run tests
script:
  - flake8 bci tests --exclude=bci/utils/protobuf
  - pytest -v --cov=./
  - codecov
  
jobs:
  include:
    - stage: flake8 test
      install: pip install flake8
      script: flake8
